// source: calculate.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.calculate.MatrixRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.calculate.Array');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculate.MatrixRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.calculate.MatrixRequest.repeatedFields_, null);
};
goog.inherits(proto.calculate.MatrixRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculate.MatrixRequest.displayName = 'proto.calculate.MatrixRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.calculate.MatrixRequest.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculate.MatrixRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.calculate.MatrixRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculate.MatrixRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculate.MatrixRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    matrix1List: jspb.Message.toObjectList(msg.getMatrix1List(),
    proto.calculate.Array.toObject, includeInstance),
    matrix2List: jspb.Message.toObjectList(msg.getMatrix2List(),
    proto.calculate.Array.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculate.MatrixRequest}
 */
proto.calculate.MatrixRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculate.MatrixRequest;
  return proto.calculate.MatrixRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculate.MatrixRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculate.MatrixRequest}
 */
proto.calculate.MatrixRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.calculate.Array;
      reader.readMessage(value,proto.calculate.Array.deserializeBinaryFromReader);
      msg.addMatrix1(value);
      break;
    case 2:
      var value = new proto.calculate.Array;
      reader.readMessage(value,proto.calculate.Array.deserializeBinaryFromReader);
      msg.addMatrix2(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculate.MatrixRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculate.MatrixRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculate.MatrixRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculate.MatrixRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMatrix1List();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.calculate.Array.serializeBinaryToWriter
    );
  }
  f = message.getMatrix2List();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.calculate.Array.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Array matrix1 = 1;
 * @return {!Array<!proto.calculate.Array>}
 */
proto.calculate.MatrixRequest.prototype.getMatrix1List = function() {
  return /** @type{!Array<!proto.calculate.Array>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.calculate.Array, 1));
};


/**
 * @param {!Array<!proto.calculate.Array>} value
 * @return {!proto.calculate.MatrixRequest} returns this
*/
proto.calculate.MatrixRequest.prototype.setMatrix1List = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.calculate.Array=} opt_value
 * @param {number=} opt_index
 * @return {!proto.calculate.Array}
 */
proto.calculate.MatrixRequest.prototype.addMatrix1 = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.calculate.Array, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.calculate.MatrixRequest} returns this
 */
proto.calculate.MatrixRequest.prototype.clearMatrix1List = function() {
  return this.setMatrix1List([]);
};


/**
 * repeated Array matrix2 = 2;
 * @return {!Array<!proto.calculate.Array>}
 */
proto.calculate.MatrixRequest.prototype.getMatrix2List = function() {
  return /** @type{!Array<!proto.calculate.Array>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.calculate.Array, 2));
};


/**
 * @param {!Array<!proto.calculate.Array>} value
 * @return {!proto.calculate.MatrixRequest} returns this
*/
proto.calculate.MatrixRequest.prototype.setMatrix2List = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.calculate.Array=} opt_value
 * @param {number=} opt_index
 * @return {!proto.calculate.Array}
 */
proto.calculate.MatrixRequest.prototype.addMatrix2 = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.calculate.Array, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.calculate.MatrixRequest} returns this
 */
proto.calculate.MatrixRequest.prototype.clearMatrix2List = function() {
  return this.setMatrix2List([]);
};


